### ISSUE TITLE
Cambiar fondo del hr

### ISSUE THREAD

**Issue by SebDevper** [frutillitaclub/menu_dinamico#1]
# color
El color del hr no combina con el fondo del menú, cambiar a verde.
El cambio se tiene que hacer en css->`main article hr`

**Comment by asder707** [comment]
Creo que tienes razón, se vería muy sexy

**Comment by SebDevper** [comment]
eso se vería muy sexy 1313 :boom:

**Comment by SebDevper** [comment]
:tophat:

**Comment by SebDevper** [comment]
En verde se vio mucho mejor 💃
